/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RdPElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RdP");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRdPKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTransicionesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTransicionesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTransicionesTransicionParserRuleCall_4_0 = (RuleCall)cTransicionesAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTransicionesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTransicionesTransicionParserRuleCall_5_1_0 = (RuleCall)cTransicionesAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLugaresKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cLugaresAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cLugaresLugarParserRuleCall_9_0 = (RuleCall)cLugaresAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cLugaresAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cLugaresLugarParserRuleCall_10_1_0 = (RuleCall)cLugaresAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cArcosKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cArcosAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cArcosArcoParserRuleCall_14_0 = (RuleCall)cArcosAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cArcosAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cArcosArcoParserRuleCall_15_1_0 = (RuleCall)cArcosAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//RdP returns rdp::RdP:
		//    'RdP'
		//    '{'
		//        'transiciones' '{' transiciones+=Transicion ( "," transiciones+=Transicion)* '}'
		//        'lugares' '{' lugares+=Lugar ( "," lugares+=Lugar)* '}'
		//        'arcos' '{' arcos+=Arco ( "," arcos+=Arco)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'RdP'
		//'{'
		//    'transiciones' '{' transiciones+=Transicion ( "," transiciones+=Transicion)* '}'
		//    'lugares' '{' lugares+=Lugar ( "," lugares+=Lugar)* '}'
		//    'arcos' '{' arcos+=Arco ( "," arcos+=Arco)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'RdP'
		public Keyword getRdPKeyword_0() { return cRdPKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'transiciones'
		public Keyword getTransicionesKeyword_2() { return cTransicionesKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//transiciones+=Transicion
		public Assignment getTransicionesAssignment_4() { return cTransicionesAssignment_4; }
		
		//Transicion
		public RuleCall getTransicionesTransicionParserRuleCall_4_0() { return cTransicionesTransicionParserRuleCall_4_0; }
		
		//( "," transiciones+=Transicion)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//transiciones+=Transicion
		public Assignment getTransicionesAssignment_5_1() { return cTransicionesAssignment_5_1; }
		
		//Transicion
		public RuleCall getTransicionesTransicionParserRuleCall_5_1_0() { return cTransicionesTransicionParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'lugares'
		public Keyword getLugaresKeyword_7() { return cLugaresKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//lugares+=Lugar
		public Assignment getLugaresAssignment_9() { return cLugaresAssignment_9; }
		
		//Lugar
		public RuleCall getLugaresLugarParserRuleCall_9_0() { return cLugaresLugarParserRuleCall_9_0; }
		
		//( "," lugares+=Lugar)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//lugares+=Lugar
		public Assignment getLugaresAssignment_10_1() { return cLugaresAssignment_10_1; }
		
		//Lugar
		public RuleCall getLugaresLugarParserRuleCall_10_1_0() { return cLugaresLugarParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'arcos'
		public Keyword getArcosKeyword_12() { return cArcosKeyword_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//arcos+=Arco
		public Assignment getArcosAssignment_14() { return cArcosAssignment_14; }
		
		//Arco
		public RuleCall getArcosArcoParserRuleCall_14_0() { return cArcosArcoParserRuleCall_14_0; }
		
		//( "," arcos+=Arco)*
		public Group getGroup_15() { return cGroup_15; }
		
		//","
		public Keyword getCommaKeyword_15_0() { return cCommaKeyword_15_0; }
		
		//arcos+=Arco
		public Assignment getArcosAssignment_15_1() { return cArcosAssignment_15_1; }
		
		//Arco
		public RuleCall getArcosArcoParserRuleCall_15_1_0() { return cArcosArcoParserRuleCall_15_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class ArcoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Arco");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cArco_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cArcoTLParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cArcoLTParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Arco returns rdp::Arco:
		//    Arco_Impl | ArcoTL | ArcoLT;
		@Override public ParserRule getRule() { return rule; }
		
		//Arco_Impl | ArcoTL | ArcoLT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Arco_Impl
		public RuleCall getArco_ImplParserRuleCall_0() { return cArco_ImplParserRuleCall_0; }
		
		//ArcoTL
		public RuleCall getArcoTLParserRuleCall_1() { return cArcoTLParserRuleCall_1; }
		
		//ArcoLT
		public RuleCall getArcoLTParserRuleCall_2() { return cArcoLTParserRuleCall_2; }
	}
	public class TransicionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Transicion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTransicionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTransicionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Transicion returns rdp::Transicion:
		//    {rdp::Transicion}
		//    'Transicion'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{rdp::Transicion}
		//'Transicion'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{rdp::Transicion}
		public Action getTransicionAction_0() { return cTransicionAction_0; }
		
		//'Transicion'
		public Keyword getTransicionKeyword_1() { return cTransicionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class LugarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Lugar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLugarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMarcaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMarcaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMarcaEIntParserRuleCall_4_0 = (RuleCall)cMarcaAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Lugar returns rdp::Lugar:
		//    'Lugar'
		//    name=EString
		//    '{'
		//        'marca' marca=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Lugar'
		//name=EString
		//'{'
		//    'marca' marca=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Lugar'
		public Keyword getLugarKeyword_0() { return cLugarKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'marca'
		public Keyword getMarcaKeyword_3() { return cMarcaKeyword_3; }
		
		//marca=EInt
		public Assignment getMarcaAssignment_4() { return cMarcaAssignment_4; }
		
		//EInt
		public RuleCall getMarcaEIntParserRuleCall_4_0() { return cMarcaEIntParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class Arco_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Arco_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cArcoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPesoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPesoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPesoEIntParserRuleCall_3_0 = (RuleCall)cPesoAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Arco_Impl returns rdp::Arco:
		//    'Arco'
		//    '{'
		//        'peso' peso=EInt
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Arco'
		//'{'
		//    'peso' peso=EInt
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Arco'
		public Keyword getArcoKeyword_0() { return cArcoKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'peso'
		public Keyword getPesoKeyword_2() { return cPesoKeyword_2; }
		
		//peso=EInt
		public Assignment getPesoAssignment_3() { return cPesoAssignment_3; }
		
		//EInt
		public RuleCall getPesoEIntParserRuleCall_3_0() { return cPesoEIntParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class ArcoTLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ArcoTL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cArcoTLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPesoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPesoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPesoEIntParserRuleCall_3_0 = (RuleCall)cPesoAssignment_3.eContents().get(0);
		private final Keyword cOrigenKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOrigenAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cOrigenTransicionCrossReference_5_0 = (CrossReference)cOrigenAssignment_5.eContents().get(0);
		private final RuleCall cOrigenTransicionEStringParserRuleCall_5_0_1 = (RuleCall)cOrigenTransicionCrossReference_5_0.eContents().get(1);
		private final Keyword cDestinoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDestinoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cDestinoLugarCrossReference_7_0 = (CrossReference)cDestinoAssignment_7.eContents().get(0);
		private final RuleCall cDestinoLugarEStringParserRuleCall_7_0_1 = (RuleCall)cDestinoLugarCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ArcoTL returns rdp::ArcoTL:
		//    'ArcoTL'
		//    '{'
		//        'peso' peso=EInt
		//        'origen' origen=[rdp::Transicion|EString]
		//        'destino' destino=[rdp::Lugar|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ArcoTL'
		//'{'
		//    'peso' peso=EInt
		//    'origen' origen=[rdp::Transicion|EString]
		//    'destino' destino=[rdp::Lugar|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ArcoTL'
		public Keyword getArcoTLKeyword_0() { return cArcoTLKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'peso'
		public Keyword getPesoKeyword_2() { return cPesoKeyword_2; }
		
		//peso=EInt
		public Assignment getPesoAssignment_3() { return cPesoAssignment_3; }
		
		//EInt
		public RuleCall getPesoEIntParserRuleCall_3_0() { return cPesoEIntParserRuleCall_3_0; }
		
		//'origen'
		public Keyword getOrigenKeyword_4() { return cOrigenKeyword_4; }
		
		//origen=[rdp::Transicion|EString]
		public Assignment getOrigenAssignment_5() { return cOrigenAssignment_5; }
		
		//[rdp::Transicion|EString]
		public CrossReference getOrigenTransicionCrossReference_5_0() { return cOrigenTransicionCrossReference_5_0; }
		
		//EString
		public RuleCall getOrigenTransicionEStringParserRuleCall_5_0_1() { return cOrigenTransicionEStringParserRuleCall_5_0_1; }
		
		//'destino'
		public Keyword getDestinoKeyword_6() { return cDestinoKeyword_6; }
		
		//destino=[rdp::Lugar|EString]
		public Assignment getDestinoAssignment_7() { return cDestinoAssignment_7; }
		
		//[rdp::Lugar|EString]
		public CrossReference getDestinoLugarCrossReference_7_0() { return cDestinoLugarCrossReference_7_0; }
		
		//EString
		public RuleCall getDestinoLugarEStringParserRuleCall_7_0_1() { return cDestinoLugarEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ArcoLTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ArcoLT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cArcoLTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPesoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPesoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPesoEIntParserRuleCall_3_0 = (RuleCall)cPesoAssignment_3.eContents().get(0);
		private final Keyword cOrigenKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cOrigenAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cOrigenLugarCrossReference_5_0 = (CrossReference)cOrigenAssignment_5.eContents().get(0);
		private final RuleCall cOrigenLugarEStringParserRuleCall_5_0_1 = (RuleCall)cOrigenLugarCrossReference_5_0.eContents().get(1);
		private final Keyword cDestinoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDestinoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cDestinoTransicionCrossReference_7_0 = (CrossReference)cDestinoAssignment_7.eContents().get(0);
		private final RuleCall cDestinoTransicionEStringParserRuleCall_7_0_1 = (RuleCall)cDestinoTransicionCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//ArcoLT returns rdp::ArcoLT:
		//    'ArcoLT'
		//    '{'
		//        'peso' peso=EInt
		//        'origen' origen=[rdp::Lugar|EString]
		//        'destino' destino=[rdp::Transicion|EString]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ArcoLT'
		//'{'
		//    'peso' peso=EInt
		//    'origen' origen=[rdp::Lugar|EString]
		//    'destino' destino=[rdp::Transicion|EString]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ArcoLT'
		public Keyword getArcoLTKeyword_0() { return cArcoLTKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'peso'
		public Keyword getPesoKeyword_2() { return cPesoKeyword_2; }
		
		//peso=EInt
		public Assignment getPesoAssignment_3() { return cPesoAssignment_3; }
		
		//EInt
		public RuleCall getPesoEIntParserRuleCall_3_0() { return cPesoEIntParserRuleCall_3_0; }
		
		//'origen'
		public Keyword getOrigenKeyword_4() { return cOrigenKeyword_4; }
		
		//origen=[rdp::Lugar|EString]
		public Assignment getOrigenAssignment_5() { return cOrigenAssignment_5; }
		
		//[rdp::Lugar|EString]
		public CrossReference getOrigenLugarCrossReference_5_0() { return cOrigenLugarCrossReference_5_0; }
		
		//EString
		public RuleCall getOrigenLugarEStringParserRuleCall_5_0_1() { return cOrigenLugarEStringParserRuleCall_5_0_1; }
		
		//'destino'
		public Keyword getDestinoKeyword_6() { return cDestinoKeyword_6; }
		
		//destino=[rdp::Transicion|EString]
		public Assignment getDestinoAssignment_7() { return cDestinoAssignment_7; }
		
		//[rdp::Transicion|EString]
		public CrossReference getDestinoTransicionCrossReference_7_0() { return cDestinoTransicionCrossReference_7_0; }
		
		//EString
		public RuleCall getDestinoTransicionEStringParserRuleCall_7_0_1() { return cDestinoTransicionEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	
	private final RdPElements pRdP;
	private final ArcoElements pArco;
	private final TransicionElements pTransicion;
	private final LugarElements pLugar;
	private final Arco_ImplElements pArco_Impl;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final ArcoTLElements pArcoTL;
	private final ArcoLTElements pArcoLT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRdP = new RdPElements();
		this.pArco = new ArcoElements();
		this.pTransicion = new TransicionElements();
		this.pLugar = new LugarElements();
		this.pArco_Impl = new Arco_ImplElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.pArcoTL = new ArcoTLElements();
		this.pArcoLT = new ArcoLTElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RdP returns rdp::RdP:
	//    'RdP'
	//    '{'
	//        'transiciones' '{' transiciones+=Transicion ( "," transiciones+=Transicion)* '}'
	//        'lugares' '{' lugares+=Lugar ( "," lugares+=Lugar)* '}'
	//        'arcos' '{' arcos+=Arco ( "," arcos+=Arco)* '}'
	//    '}';
	public RdPElements getRdPAccess() {
		return pRdP;
	}
	
	public ParserRule getRdPRule() {
		return getRdPAccess().getRule();
	}
	
	//Arco returns rdp::Arco:
	//    Arco_Impl | ArcoTL | ArcoLT;
	public ArcoElements getArcoAccess() {
		return pArco;
	}
	
	public ParserRule getArcoRule() {
		return getArcoAccess().getRule();
	}
	
	//Transicion returns rdp::Transicion:
	//    {rdp::Transicion}
	//    'Transicion'
	//    name=EString;
	public TransicionElements getTransicionAccess() {
		return pTransicion;
	}
	
	public ParserRule getTransicionRule() {
		return getTransicionAccess().getRule();
	}
	
	//Lugar returns rdp::Lugar:
	//    'Lugar'
	//    name=EString
	//    '{'
	//        'marca' marca=EInt
	//    '}';
	public LugarElements getLugarAccess() {
		return pLugar;
	}
	
	public ParserRule getLugarRule() {
		return getLugarAccess().getRule();
	}
	
	//Arco_Impl returns rdp::Arco:
	//    'Arco'
	//    '{'
	//        'peso' peso=EInt
	//    '}';
	public Arco_ImplElements getArco_ImplAccess() {
		return pArco_Impl;
	}
	
	public ParserRule getArco_ImplRule() {
		return getArco_ImplAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//ArcoTL returns rdp::ArcoTL:
	//    'ArcoTL'
	//    '{'
	//        'peso' peso=EInt
	//        'origen' origen=[rdp::Transicion|EString]
	//        'destino' destino=[rdp::Lugar|EString]
	//    '}';
	public ArcoTLElements getArcoTLAccess() {
		return pArcoTL;
	}
	
	public ParserRule getArcoTLRule() {
		return getArcoTLAccess().getRule();
	}
	
	//ArcoLT returns rdp::ArcoLT:
	//    'ArcoLT'
	//    '{'
	//        'peso' peso=EInt
	//        'origen' origen=[rdp::Lugar|EString]
	//        'destino' destino=[rdp::Transicion|EString]
	//    '}';
	public ArcoLTElements getArcoLTAccess() {
		return pArcoLT;
	}
	
	public ParserRule getArcoLTRule() {
		return getArcoLTAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
