/**
 * generated by Xtext 2.15.0
 */
package pnpl_variability.ide;

import pnpl_variability.ide.AbstractPNPL_variabilityIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PNPL_variabilityIdeModule extends AbstractPNPL_variabilityIdeModule {
}
