/**
 * generated by Xtext 2.15.0
 */
package pnpl_variability.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pnpl_variability.PNPL_variabilityRuntimeModule;
import pnpl_variability.PNPL_variabilityStandaloneSetup;
import pnpl_variability.ide.PNPL_variabilityIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PNPL_variabilityIdeSetup extends PNPL_variabilityStandaloneSetup {
  @Override
  public Injector createInjector() {
    PNPL_variabilityRuntimeModule _pNPL_variabilityRuntimeModule = new PNPL_variabilityRuntimeModule();
    PNPL_variabilityIdeModule _pNPL_variabilityIdeModule = new PNPL_variabilityIdeModule();
    return Guice.createInjector(Modules2.mixin(_pNPL_variabilityRuntimeModule, _pNPL_variabilityIdeModule));
  }
}
