/**
 * generated by Xtext 2.15.0
 */
package pnpl_variability.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pnpl_variability.ui.AbstractPNPL_variabilityUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PNPL_variabilityUiModule extends AbstractPNPL_variabilityUiModule {
  public PNPL_variabilityUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
